---
title: "CCamps - Concentration Camp System Locations"
author: "Rachel Van Nostrand"
date: "Updated May 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(leaflet)
library(tidyverse)
library(dplyr)
library(sp)
library(rjson)
library(rgdal)
library(sf)
library(terra)
library(raster)
library(htmlwidgets)
library(leaflet.extras)
library(mapview)
library(sfheaders)

states45 <- st_read("/Users/rachelvannostrand/Documents/NSF/Maps/mappy2.shp")


state_popup_2 <- ifelse(states45$CAMPS >= 1, 
                         paste0("<strong>Country: </strong>", 
                      states45$NAME, 
                      "<br><strong>Concentration Camp(s): </strong>", 
                      states45$CAMPS,
                      "<br><strong> Start Year: </strong>", 
                      states45$START_YEAR),
                         paste0( "<br><strong> Country: </strong>", 
                      states45$NAME))

Concentration_Camp_Systems <- leaflet(states45) %>%
  addTiles() %>% 
  addPolygons(color = "#444444", weight = 1, popup = state_popup_2, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              fillColor = ~colorBin("YlOrRd", CAMPS)(CAMPS),
              highlightOptions = highlightOptions(color = "white", weight = 2,
                                                  bringToFront = TRUE))
```

```{r}

Concentration_Camp_Systems


```
